development:
  adapter: postgresql
  encoding: unicode
  database: <%=  ENV['DB_HOST_DEV'] %>
  pool: 5
  username: <%=  ENV['DB_USERNAME'] %>
  password: <%=  ENV['DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%=  ENV['DB_HOST_TEST'] %>
  pool: 5
  username: <%=  ENV['DB_USERNAME'] %>
  password: <%=  ENV['DB_PASSWORD'] %>
